site_name: "Guide to Redis"
site_description: "A comprehensive guide to Redis for freshers and beginners"
site_author: "Mitarpal Grover"
site_url: https://mydomain.org/mysite

nav:
  - Welcome to Redis : index.md
  - Getting Started : 
    - What is Redis? : getting-started/what_is_redis.md
    - Installation : getting-started/redis_installation.md
    - First Step : getting-started/redis_first_steps.md
    - Redis CLI Basics : getting-started/redis_cli_basics.md
  - Fundamentals :
    - Redis Datatypes : fundamentals/redis_data_types.md
    - Keys And Values : fundamentals/redis_keys_values.md
    - Memory Persistence : fundamentals/redis_memory_persistence.md
    - Configuration Basics : fundamentals/redis_configuration_basics.md
  - Core Concepts :
    - Commands Overview : core-concepts/commands-overview.md


repo_url: https://github.com/MITARPALGROVER/redis-documentation.git
repo_name: MITARPALGROVER/redis

extra:
  social:
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/mitarpalgrover
    - icon: fontawesome/brands/youtube
      link: https://youtube.com
  generator: false

copyright: Copyright &copy; 2025 - 2028 Mitarpal Grover

theme:

  name: material

  language: en
  
  icon:
    repo: fontawesome/brands/github
  
  features:
    - navigation.instant
    - navigation.instant.progress
    - search.suggest
    - search.highlight
    - search.share
    - navigation.footer
    # - navigation.tabs
    - navigation.top
    # - toc.integrate
    - content.tabs.link
    - content.code.copy
    - toc.follow
    - content.code.select
    - content.code.annotate
    



  font:
    text: Poppins
    code: Roboto Mono

  logo: assets/logo.png
  favicon: assets/favicon.ico

  palette: 
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/weather-night
        name: "Switch to dark mode"

    - media: "(prefers-color-scheme: dark)"
      primary: black
      scheme: slate
      toggle:
        icon: material/weather-sunny
        name: "Switch to light mode"

markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - tables
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.keys