site_name: OpenSource Technology Redis
nav:
  - Home : index.md
  - Introduction : instruction.md
  - Installation & Setup : installation.md
  - Getting Started (Basics) : gettingstarted.md
  - Hands-On Examples : handson.md
  - Advanced Concepts  : advanced.md
  - Best Practices  : bestpractices.md
  - Resources  : resourcse.md
  - About  : about.md

site_url: https://mydomain.org/mysite
theme:
  name: material
  palette: 
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/weather-night
        name: "Switch to dark mode"
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/weather-sunny
        name: "Switch to light mode"